services:
  frontend:
    image: nginx
    container_name: "frontend"
    ports:
      - 80:80
    restart: always
    volumes:
      - /home/khadas/patrik-unchained/frontend/nginx.conf:/etc/nginx/nginx.conf

  patrik-move:
    build:
      dockerfile_inline: |
        FROM python:3.11
        WORKDIR /code
        COPY  /home/khadas/patrik-unchained/requirements.txt /code/requirements.txt
        RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
        CMD ["fastapi", "run", "app/main.py", "--port", "80"]
    container_name: patrik-move
    restart: always
    # ports:
    #  - "9001:80"
    volumes:
     - /home/khadas/patrik-unchained/app:/code/app
    devices:
    - "/dev/ttyUSB0:/dev/ttyUSB0"

  patrik-ui:
    image: joseluisq/static-web-server:2-alpine
    container_name: patrik-ui
    # ports:
    #   - 9002:80
    restart: always
    environment:l
      - SERVER_ROOT=/var/public
      - SERVER_CONFIG_FILE=/etc/config.toml
    volumes:
      - /home/khadas/patrik-unchained/patrik-ui:/var/public
      - /home/khadas/patrik-unchained/patrik-ui/config.toml:/etc/config.toml

  patrik-video:
    container_name: "patrik-video"
    restart: always
    ports:
      - "8081:8081"
      - "8765:8765"
    image: ghcr.io/motioneye-project/motioneye:edge
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
    volumes:
      - /etc/localtime:/etc/localtime:ro