services:

  patrik-move:
    build:
      dockerfile_inline: |
        FROM python:3.11
        WORKDIR /code
        COPY  /home/khadas/patrik-unchained/requirements.txt /code/requirements.txt
        RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
        CMD ["fastapi", "run", "app/main.py", "--port", "9001"]
    container_name: patrik-move
    network_mode: host
    restart: always
    # ports:
    #  - "9001:80"
    volumes:
     - /home/khadas/patrik-unchained/app:/code/app
    devices:
    - "/dev/ttyUSB0:/dev/ttyUSB0"

  traefik:
    container_name: traefik
    network_mode: host
    image: "traefik:v2.11"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    # ports:
    #   - "80:80"
    #   - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  # patrik-ui:
  #   image: joseluisq/static-web-server:2-alpine
  #   container_name: patrik-ui
  #   network_mode: host
  #   # ports:
  #   #   - 80:80
  #   restart: always
  #   environment:
  #     # Note: those envs are customizable but also optional
  #     - SERVER_ROOT=/var/public
  #     - SERVER_CONFIG_FILE=/etc/config.toml
  #   volumes:
  #     - /home/khadas/patrik-unchained/patrik-ui:/var/public
  #     - /home/khadas/patrik-unchained/patrik-ui/config.toml:/etc/config.toml

  patrik-ui:
    image: joseluisq/static-web-server:2
    container_name: patrik-ui
    network_mode: host
    environment:
      # Note: those envs are customizable but also optional
      - SERVER_ROOT=/public
    volumes:
      - /home/khadas/patrik-unchained/patrik-ui:/var/public
      # Or use an existing Docker volume
      # - website_data:/public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.website.entrypoints=web"
      - "traefik.http.routers.website.rule=Host(`website.localhost`)"
      - "traefik.http.routers.website.priority=1"
      - "traefik.http.services.website.loadbalancer.server.port=80"

  patrik-video:
    network_mode: host
    container_name: "patrik-video"
    restart: always
    # ports:
    #   - "8081:8081"
    #   - "8765:8765"
    image: ghcr.io/motioneye-project/motioneye:edge
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
    volumes:
      - /etc/localtime:/etc/localtime:ro