x-var: &DIR
  /home/khadas/patrik-unchained

services:

  patrik-move:
    build:
      dockerfile_inline: |
        FROM python:3.11
        WORKDIR /code
        COPY ${DIR}/requirements.txt /code/requirements.txt
        RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
        CMD ["fastapi", "run", "app/main.py", "--port", "9001"]
    container_name: patrik-move
    network_mode: host
    restart: always
    # ports:
    #  - "9000:80"
    volumes:
     - ${DIR}/app:/code/app
    devices:
    - "/dev/ttyUSB0:/dev/ttyUSB0"

  patrik-ui:
    image: joseluisq/static-web-server:2-alpine
    container_name: patrik-ui
    network_mode: host
    # ports:
    #   - 80:80
    restart: always
    environment:
      # Note: those envs are customizable but also optional
      - SERVER_ROOT=/var/public
      # - SERVER_CONFIG_FILE=/etc/config.toml
    volumes:
      - ${DIR}/patrik-ui:/var/public
      # - ./config.toml:/etc/config.toml

  patrik-video:
    network_mode: host
    container_name: "patrik-video"
    restart: always
    # ports:
    #   - "8081:8081"
    #   - "8765:8765"
    image: ghcr.io/motioneye-project/motioneye:edge
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
    volumes:
      - /etc/localtime:/etc/localtime:ro