version: '3'

services:

  patrik-move:
    build: .
    container_name: "patrik-move"
    restart: always
    ports:
     - "80:80"
    volumes:
     - /home/khadas/patrik-unchained/app:/code/app
    devices:
    - "/dev/ttyUSB0:/dev/ttyUSB0"

  patrik-ui:
    image: joseluisq/static-web-server:2-alpine
    container_name: "patrik-ui"
    ports:
      - 8888:80
    restart: always
    environment:
      # Note: those envs are customizable but also optional
      - SERVER_ROOT=/var/public
      # - SERVER_CONFIG_FILE=/etc/config.toml
    volumes:
      - $HOME/patrik-unchained/patrik-ui:/var/public
      # - ./config.toml:/etc/config.toml