services:
  patrik-face:
      build:
        context: .
        dockerfile_inline: |
          FROM python:3.11
          WORKDIR /code
          COPY  ./requirements.txt /code/requirements.txt
          RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
          CMD ["fastapi", "run", "app/main.py", "--port", "80"]
      container_name: patrik-face
      restart: always
      volumes:
      - ./app:/code/app