from enum import Enum


class ModelExpression(str, Enum):
    annoyed = "annoyed"
    anxious = "anxious"
    apologetic = "apologetic"
    awkward = "awkward"
    blinking = "blinking"
    bored = "bored"
    crying = "crying"
    default = "default"
    determined = "determined"
    embarrased = "embarrased"
    evil = "evil"
    excited = "excited", 
    exhausted = "exhausted"
    flustered = "flustered"
    furious = "furious"
    giggle = "giggle"
    happy = "happy"
    in_love = "in-love"
    mischievous = "mischievous"
    realized_something = "realized-something"
    sad = "sad"
    sassy = "sassy"
    scared = "scared"
    shocked = "shocked"
    snoozing = "snoozing"
    starstruck = "starstruck"
    stuck_up = "stuck-up"
    thinking = "thinking"
    tired = "tired"
    upset = "upset"
    winking = "winking"
    wow = "wow"