services:
  patrik-pyside6:
    build:
      context: .
      dockerfile_inline: |
        FROM python:3.11

        RUN adduser --quiet --disabled-password qtuser && usermod -a -G qtuser
        RUN apt update && apt install -y \
          libxcb-cursor-dev \
          libxcb-cursor0 \
          libxkbfile-dev \
          libasound2 \
          libxtst6 \
          libxrandr2 \
          libxdamage1 \
          libnss3 \
          libxcomposite-dev \
          libgl1-mesa-glx \
          libxkbcommon-x11-0 \
          libxcb-icccm4 \
          libxcb-image0 \
          libxcb-keysyms1 \
          libxcb-randr0 \
          libxcb-render-util0 \
          libxcb-render0 \
          libxcb-shape0 \
          libxcb-sync1 \
          libxcb-xfixes0 \
          libxcb-xinerama0 \
          libxcb-xkb1 \
          libxcb1 \
          libxrender1 \
          libxi6 \
          libdbus-1-3 \
          libxcb-cursor0 \
          libegl1 \  
        && apt-get clean \
        && rm -rf /var/lib/apt/lists/*

        WORKDIR /code
        COPY  ./requirements.txt /code/requirements.txt
        RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
        CMD ["python", "app/main.py"]

    container_name: patrik-pyside6
    user: qtuser
    restart: always
    environment:
      - DISPLAY=${DISPLAY}
      - ENV QT_DEBUG_PLUGINS=1
      # - ENV QT_QPA_PLATFORM=xcb
      - ENV QTWEBENGINE_DISABLE_SANDBOX=1
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_INDIRECT=0
    volumes:
     - ./app:/code/app
     - /tmp/.X11-unix:/tmp/.X11-unix
