services:
  patrik-pyside6:
    build:
      context: .
      dockerfile_inline: |
        FROM python:3.11

        RUN groupadd --gid 1000 qtuser \
        && useradd --uid 1000 --gid 1000 -m qtuser \
        && apt-get update \
        && apt-get install -y sudo \
        && echo qtuser ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/qtuser \
        && chmod 0440 /etc/sudoers.d/qtuser

        USER qtuser

        RUN sudo apt install -y \
        libxcb-cursor0 \
        libxkbfile-dev \
        libasound2 \
        libxtst6 \
        libxrandr2 \
        libxdamage1 \
        libnss3 \
        libxcomposite-dev \
        libgl1-mesa-glx \
        libxkbcommon-x11-0 \
        libxcb-icccm4 \
        libxcb-image0 \
        libxcb-keysyms1 \
        libxcb-randr0 \
        libxcb-render-util0 \
        libxcb-render0 \
        libxcb-shape0 \
        libxcb-sync1 \
        libxcb-xfixes0 \
        libxcb-xinerama0 \
        libxcb-xkb1 \
        libxcb1 \
        libxrender1 \
        libxi6 \
        libdbus-1-3 \
        libxcb-cursor0 \
        libegl1 \  
        && sudo apt-get clean \
        && sudo rm -rf /var/lib/apt/lists/*

        WORKDIR /code
        COPY  ./requirements.txt /code/requirements.txt
        RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
        CMD ["python", "app/main.py"]

    container_name: patrik-pyside6
    user: qtuser
    restart: always
    environment:
      - DISPLAY=unix$DISPLAY
      - /tmp/.X11-unix:/tmp/.X11-unix
      - QT_DEBUG_PLUGINS=1
    volumes:
     - ./app:/code/app
